sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls

env:
  global:
    - secure: EseIhUhWPtgmn95KKwlxFuELDizj6jHYlr+g7LAU/bMOB+Cu3G6M116RrNFmMpHkEA+xgDH5k73lx6HAA2sKx6fV7pRKLmXux8SRwLfkXfoiW0r+fa4Ed8Twuz0wWk6rvD7ctWtxWawgYfj8o66SVs1JR4aDMQvILEpELqwu9pBsH0qfGSHAIVbSHBDwDK0JbrswTDMsZKFK737pjhE+gzPx6CF5Dl8on1oehI0Nx3Kl5YqAHdZRvZfwu0c0HpMPJURr1d+zllZeObnsiLehdolnFkdncojHb8MKLpLPbg9jhjwceo6ck1++ioLDEYgeBxMSzza3lOBDYMv2L/IPMcdbVRZ4RmdigkQkBLaZd2O1DwD0Fae7ODM/6UdJK+0igQLJm0qL30/zS7yW2BfCIFRmXz8UyHq1ndX+iCr8B9qYnhaoV/O9oo3r5fUEldFBMXzteGCOSMCE9wUdoepj89Mx9u1ejDngTPB+tEvk6ru1WnSfzDJJ1+YwJt7L2i0yfmbMBrltg+G8uF6v8tvZ26uhZC3f/eKt+Wqv3EdxTRTwGrvObeL1uh2lXX38xUnMe0mEM4tbf1pddGuL9zIsRaI1CcbL0AK1JmFXerjt8yFzW0IyU11yH9vc70ccSIox65m85bhGxErCQ8M5OeTybEQJZ/58KehUdddGGxxPgWM=
    - secure: vLjIbL+Bt4E75wCGA8tXvsIr2s4lhRgVwmvh0Pi/l420X/gnKjDKgKZGdMFuHB7KseoNFJisjZb+tybVoW2UgXQ5fIRqL6k3eedpbHzJXIv8Lc4uk5gjBm5Dr93nOYqW2wtRfedzW17KEu4TuR0Q4bB+JYxcGi5CzvclWwyTpLBT2YYU03zZibYscuC7nnIw1EzmGje8eL7g1e5YYRYRWvcPgYV9VrBm8nOJjnO7KiAlLaxrdYZ4KfgKuQPi8IxTa+zG4zP26WCbylGJUeUQLoNMKAQmcA8tqxmx23E2ei2Cw9ZxoflNOj4zkKiBzngtZ0HhZpvVKaq3WdOqeQSckke9Z8NT8skot7XeIszZHX7GT36ES1IMYyFX9OYu7W19lZp78M+PIKTOV2U1o2N98JSJS9EdM2cW0Ba4hB/XJZFAbX3cEwS6HMqVjj6NNkRgYV/lFdSzbZijG0aHX8UQbEzpEpPU+zbzsLoJlrEndzWXlXCGShVXGbHjfqE/gR6UquilxAJ5c4AMixJyGkwkE+k6+TmWRAGobsThgLvdUpwU1RuEEpcvIrbokXADRicd6/WAK4ypOyDpY8XyIuajb03SxmWv1oPsLCxkF5UlQkftluHNqt+0wWkW6oVRgMnF9I1yHk3gluDQ1uukwKYXqdjLi81f+mK3dO6rnIc9fCA=
    - secure: Z0flHVoTBwxSV5DYX3J2gNLZguDvmeJu0TLWK44XV35thW1ODsdnC96hBPUXwmQanbJPrMlszVoOxlUwmdLaZPtcn2HIc12LVomyPP+q/Fs+PFWLDOBHQrRjm7YVhObinMBvGgPhSMXhBv4CseDVIjUi0pn0fzFn4SEC/vGhPtuD0mQ8tS4en9UysdXCABCu8yxEl37vIqXpVs/kvHcjREXd2i4SkBpB+uQ8VLi7faxu1s5pyrUdDKMgnTgoDSleISwh7HTpYXCGu75gCBi8Cv+eqEAmAGyb/qNrfx5AdovuUqY+sgpOe84HQa0jwdkKVqxTgWhww6OC3gkcVyA7m2989I1ZVjPsiGjhIKHRIO05qWxj+UdGhn/PB7oCVKLWtc0jBIN0POjScvYHWVvSyls1DEpzJJcy6khsd0hOcBt+JcOZQQnPYp8Ais5JmKkoiSZLnCkEZBK9UoedNk8fHLul8W08/46KEwxkjYTkP9Lec4+tXzEnGqfU7/03f0kJ9msyve8L79GfEHTX4GML+VrjULvCqM+Ql3dYXRLgXTEM8H2ebPNwao+RUtcfxZjw/klcXFQLkpXoNIKJyj/14rmmBWknrtcYtS+VRLMb1CdlL45Eo55EX0TesfAO+JG4Tn0acB6oYdezEuJTZKnkcWdvytCyiaEMm0RcK9/QxVI=
